### ISSUE TITLE
Cant use Fishing Rods with luiafk reborn

### ISSUE THREAD

**Issue by kalost07** [dragon3025/Reduced-Grinding#11]
Terraria Version: v1.4.3.6
TModLoader Version: v2022.7.58.9

**Mods Installed**
- Reduced Grinding
- Luiafk Reborn

Only bugged if both mods are enabled.

**Describe the bug**
Fishing rods don't throw bobbers and are swung like swords when I try to use them.

**To Reproduce**
1. Get a fishing rod
2. Left click (bait not needed)

**Expected behavior**
Fishing rod to throw bobber and let me fish.

**Comment by kalost07** [comment]
Apparently it's an issue with luiafk, not reduced grinding

**Comment by kalost07** [comment]
Yes there is actually an update and when I downloaded it fishing started working as expected. Haven't tested any modded rods or buffs though.

**Comment by dragon3025** [comment]
Alright, it sounds like it's all good then. My mod was unintentionally replacing amounts with new amounts, but now it adds to them, so it should work with other modded rods and buffs.
