### ISSUE TITLE
Halloween item drop chances still broken

### ISSUE THREAD

**Issue by Waluigi-Wahp** [dragon3025/Reduced-Grinding#12]
Terraria Version: 1.4.3.6
TModLoader Version: 2022.9.47.8

**Mods Installed**
- Reduced Grinding
- Nothing else

**Describe the bug**
Halloween Goodie Bags, Bladed Gloves and Bloody Machetes still have a 100% drop chance, despite the 8.10.2 update.

**To Reproduce**
1. Start any world
2. Kill any enemy
3. ???
4. Too much profit

**Expected behavior**
A significantly smaller drop chance

**Screenshots**
![image](https://user-images.githubusercontent.com/116832088/198352454-e6767582-5209-482d-8726-3a4a495e2826.png)
![image](https://user-images.githubusercontent.com/116832088/198352594-c794fbe2-98d6-40af-b5e9-7a179976f056.png)
![image](https://user-images.githubusercontent.com/116832088/198352784-298f01f0-3d46-4223-9904-68f7c08bc5fa.png)
![image](https://user-images.githubusercontent.com/116832088/198353000-6b6772f7-3305-4c53-946c-8c1d0db577ac.png)

**Comment by dragon3025** [comment]
The only lines that deal with those items is the 3 lines that you posted. The drop chance denominator is 2000, so I don't know why it would do that, but I'm not having that issue. Here's a pick of it in visual studio:
![Screenshot (287)](https://user-images.githubusercontent.com/11652210/198394212-b40e4059-26da-4d25-b235-dfa58605aa8d.png)

**Comment by Waluigi-Wahp** [comment]
I'm just as confused as you are, honestly. At one point I searched through every single mod file, comparing to both 8.10.1 and 8.9.1 to see if there was anything else potentially affecting it(there wasn't). I then tried straight up deleting those 3 lines entirely and repackaging the mod(did nothing, didn't even break anything). I've also tried redownloading terraria, the mod itself, tmodloader(with a clean wipe each time), and nothing changed. It has me completely at a loss.

**Comment by Waluigi-Wahp** [comment]
The workaround I started using is to just have them set to autotrash(thank you Sieron Satori of Steam), but it's not exactly a solution

**Comment by ScorelessPine** [comment]
8e836d7f2f39a94bc40a2490e439d93d9ddebc12 Should have solved that issue, so that's really strange. I personally saw the issue before, and had seen that it was fixed after v8.10.2 in my world. Could there possibly be any conflict relating to config settings?

**Comment by dragon3025** [comment]
I don't have any configurations for those items, it just sets it so it only requires Halloween and not weak enemies.

If you have a copy of my mod in "Documents\My Games\Terraria\tModLoader\Mods", it tModLoader will use that instead of my mod found in the in-game menu / workshop. If you have a "ReducedGrinding" tmod file in that directory, try moving it out of the folder somewhere, delete my mod from the in-game mods list, then re-download my mod from the menu.
