### ISSUE TITLE
Abyssal Whistle (Thorium) and Hel-Fire yo-yo droprate unusually high by default.

### ISSUE THREAD

**Issue by MaddieR32** [dragon3025/Reduced-Grinding#14]
Terraria Version: v1.4.3.6
TModLoader Version: v2022.9.47.23

**Mods Installed**
- Reduced Grinding
- Thorium Mod

**Describe the bug**
When fighting enemies in the underworld, the Abyssal Whistle from Thorium drops incredibly commonly from every hell enemy, when in fact it should merely have a 0.5% chance droprate. 
The Hel-Fire from base Terraria is also affected, as it has a 0.25% chance droprate, and I have quite the excess of both items after a very short trip in the Underworld.

**To Reproduce**
1. Install both Reduced Grinding and Thorium
2. Keep vanilla settings for Reduced Grinding
3. Farm for a short period in the Underworld
5. Check inventory

**Expected behavior**
As mentioned above, these drops should be a lot less common.

**Screenshots**
Screenshots wouldn't do much added justice, it's what you'd expect.

**Comment by dragon3025** [comment]
I got a report similar to this on the workshop page. My mod doesn't have any coding that would alter those chances, but to be safe I tested it out and enemy's weren't dropping Hel-Fire Yo-Yo's and Abyssal Whistle's with a 100% chance.

The person who reported the problem said they re-installed their game client (I don't know if it was Terraria, tModLoader, or both), and that fixed it, so I think it's a bug with tModLoader itself. If you reinstall, I'm pretty sure your saves and mods at "C:\Users\user_name\Documents\My Games" won't get deleted, but you can back it up first to be safe.

**Comment by MaddieR32** [comment]
Figured I should quickly mention that the droprate wasn't 100%, but it was definitely way above 0.5%, like one in every 10 or so enemies.

The issue seems to still be persisting even with both a Terraria and tModLoader reinstall. Disabling this mod fixes the issue but of course also removes the reason I installed it lol.
I'll probably just continue to play it with the friends and we'll just trash anything that spawns too much like the Bloody Machete and Bladed Claws that also suffer this issue on Halloween days. I'm just ultimately unsure why this mod affects these drops because, as you said, nothing here is affected by your mod, yet it also somehow is???

**Comment by dragon3025** [comment]
Weird, Bloody Machete and Bladed Claws is something I previously fixed. What version of my mod are you using and did you get it from the browser or this site?

**Comment by MaddieR32** [comment]
We've gotten it from the browser on steam workshop. Should I do a quick test run with the one uploaded here?

(Also not to pile on the bad news but we've now noticed lots of Cascade yo-yos dropping from Underworld enemies haha)

**Comment by dragon3025** [comment]
I'm just making sure you're using the newest version which is 8.13.1. Also, if you enter tModLoader's properties in Steam in the "Betas" tab, is it set to "none"?

Thanks for reporting icon error. I updated my mod with it fixed.

**Comment by MaddieR32** [comment]
Yep, I'm on 8.13.1 which was uploaded to Steam Workshop, and tmodloader is not on a beta branch. 

I'll see if that icon update SOMEHOW fixes droprates and edit the post for if it does.

**Comment by dragon3025** [comment]
I figured it out. The Town NPC Weapon configuration was affecting items that can be dropped by multiple enemies. For Town NPC weapons: I had a condition to test if it's a town NPC, but I didn't know I needed a condition that tested for their item because of all universally dropped items. I updated my mod and fixed the issue.

**Comment by MaddieR32** [comment]
yep, seems to be working great! thank you very much :)
