### ISSUE TITLE
Crash on player menu

### ISSUE THREAD

**Issue by DragonAce765** [dragon3025/Reduced-Grinding#27]
Terraria Version: 1.4.4.9
TModLoader Version: 2024.10.3.0
Beta: (None if not using Beta): None
Reduced Grinding Version: 9.11

**Mods Installed**
- Reduced Grinding
- Vanilla+ QoL v1.0.0.39

**Describe the bug**
I click on single player to load a character and world, and the game crashes to desktop.

**To Reproduce**
1. Load the game.
2. Load the mods.
3. Click Single Player
4. Game CTDs

**Expected behavior**
Game should not CTD and pull up the character menu.

**Screenshots**
[client.log](https://github.com/user-attachments/files/18106113/client.log)

**Additional context**
Appears to be a compatibility conflict. I've notified the dev(s) of Vanilla+ QoL as well. Game does not crash with only one mod enabled, only when both are enabled together.

**Comment by dragon3025** [comment]
https://github.com/dragon3025/Reduced-Grinding/issues/31#issue-2735462443
