### ISSUE TITLE
latest update causes game to crash when clicking on either multiplayer of singleplayer

### ISSUE THREAD

**Issue by BOLTMAGIC** [dragon3025/Reduced-Grinding#28]
Terraria Version: 1.4.4.9
TModLoader Version: v2024.10.3.0
Beta: (None if not using Beta): none
Reduced Grinding Version: v9.11

**Mods Installed**
- Reduced Grinding
- Fargos Mutant Mod v3.3.5.1

**To Reproduce**
download and enable reduced grinding and fargos mutant mod and press singleplayer

the game will crash

**Expected behavior**
to play the game

https://pastebin.com/Et8C1aXg

thx a lot!

**Comment by dragon3025** [comment]
https://github.com/dragon3025/Reduced-Grinding/issues/31#issue-2735462443
