### ISSUE TITLE
Unable to pick up items in the 1.4 tModLoader release

### ISSUE THREAD

**Issue by Overcontrol1** [dragon3025/Reduced-Grinding#3]
With Reduced Grinding as the only mod enabled, I am unable to pickup items in the 1.4 release.

**Comment by dragon3025** [comment]
I tested it out and didn't have that problem. I don't know why my mod would do that. The only item related thing my mod ever does is spawn items out of Grab Bags. Are you using the latest versions of tModLoader and my mod? At the time of writing this, it's:

- tModloader: v2022.05.103.9
- Reduced Grinding: 7.0.0.4

**Comment by Overcontrol1** [comment]
I am 100% sure that I had the latest versions of both Reduced Grinding and tModLoader. Disabling the mod fixed it. I forgot to add this in the first issue, but it only occurs in multiplayer.

**Comment by dragon3025** [comment]
I tried it in multiplayer, and didn't have the same problem. It was in tModLoader v2022.05.103.14, so I don't know if that made any difference. What items are you not able to pick up?

**Comment by Overcontrol1** [comment]
I couldn't pick up anything, from wood to stone to acorns. At the time the bug occurred, I was on tModLoader v2022.05.103.9, and it occurred whether or not there was one or more players in the session. I can see if it's still happening soon.
