### ISSUE TITLE
Game Crashes upon clicking Single player or multiplayer after update

### ISSUE THREAD

**Issue by WalmartAdine** [dragon3025/Reduced-Grinding#30]
Terraria Version: 1.4.4.9
TModLoader Version: 2024.10.3.0
Beta: (None if not using Beta):
Reduced Grinding Version: 9.11? (whatever latest is)

**Mods Installed**
- Reduced Grinding
- Any other mods (try testing with only my mod installed, to be sure my mod is causing the problem).
any combo of mods aslong as it has reduced grinding it crashes or if its the only mod

**Describe the bug**
A clear and concise description of what the bug is. Where you playing in single player when the bug happened?
it crashes the game if you click single player or multiplayer
**To Reproduce**
click singleplayer or multiplayer
**Expected behavior**
not the game crashing
**Screenshots**

**Additional context**

**Comment by dragon3025** [comment]
I'm going to continue this issue here: https://github.com/dragon3025/Reduced-Grinding/issues/31#issue-2735462443
