### ISSUE TITLE
Game crashes when loading this mod after update

### ISSUE THREAD

**Issue by Darkclawxxdeath** [dragon3025/Reduced-Grinding#31]
Terraria Version: v2024.10.3.0
TModLoader Version: v1.4.4.9
Beta: (None if not using Beta): None
Reduced Grinding Version: v9.11

Mods Installed
- Reduced Grinding
- Advanced World Generation v3.1.7.4
- Quality of Terraria 更好的体验 v1.8.0.2
- Fargo's Souls Mod v1.7.0.12
- Fargo's Mutant Mod v3.3.5.1
- Luminance v1.0.7
- Spirit Mod v1.5.0.30
- Fargo's Best of Both Worlds v0.5.2
- Dragon Ball Terraria QOL Drops v1.1.2
- Fargo's Enemy Modifiers v0.9
- Dragon Ball Terraria: Gohan Forms Addon v0.4.1
- Katana ZERO Weapons v1.2.1
- Necklace Slot v0.1.4
- Ninja and Diving Gear Slot v0.1.2
- Shorter Respawn Time v1.1.1.2
- Vyklade's DBT Transformation Lib v1.8.0
- Dragon Ball Terraria Legacy v1.0
- Dragon Ball Terraria: Super Saiyan Blue Evolution v0.5.2.1
- Subworld Library v2.2.2.2
- Vacuum Bags v1.2.4.16
- Shield Slot v1.0
- Player Ping UI v1.0.1
- Boss Checklist v2.2.2
- Calamity - Fargo's Souls DLC v1.1.1.1
- MooMoo's Ultimate Yoyo Revamp v0.2.9.6
- MooMoo's Yoyo Lib v0.1.1
- MoreZenithItems v1.3.5
- More Accessory Slots (More Accessories) v1.4.2
- Fervent Arms v0.0.0.9
- Fargo's Soul Mod Extras v0.6.2
- Wing Slot Extra v1.4.4
- Weapon Enchantments v1.0.8
- Vacuum Ore Bag v1.0.2.2
- Shop Expander v1.5.0
- Shoe Slot v1.1.0.0
- Shared World Map v0.1.4.3
- Recipe Browser v0.10.8
- Rainy's QOL v0.30
- Petrified Voodoo Doll v1.2.1
- No More Hunger v1.1
- Max Stack Plus Extra v1.4.0.3
- Koko Net Lib v0.3.3
- No More Items Stuck in Blocks v1.1
- Happiness Removal v4.0.1
- Expanded Inventory v0.4.1
- Enable Statue Farms v0.1
- Craftable Calamity Items v4.7.3.61
- Colored Fargo Relics v0.21
- Calamity's Vanities v11.1
- Better zenith in Calamity v114514.19191
- Calamity Mod Music v2.0.4.3
- Calamity Mod v2.0.4.5
- AmuletOfManyMinions v0.2
- Bountiful Goodie Bags v1.2.4
- Fargo's Banner Boost v4.0
- Basic Automated Mining v1.2.5
- Antisocial v1.6.0.3
- Angler Shops Alternative v1.0
- androLib v1.0.7.12
- Magic Storage v0.6.0.3
- absoluteAquarian Utilities v1.0.5.1
- The Amulet Of Many Minions: Combat Pets! v0.16.2

Describe the bug
Game immediately crashes when trying to load to the character selection screen. Happens when trying to play single player or multi-player.

To Reproduce

    Go to 'Workshop Hub'
    Click on 'manage mods'
    Enable both the mods listed above
    Exit to main screen
    Click either Single Player or Multi-player
    See error

Expected behavior
To be able to load into the character selection page so I can play.

**Screenshots**
![Screenshot 2024-12-12 003702](https://github.com/user-attachments/assets/9a985720-6268-4394-9ae6-22fb9d0d53b0)
![Screenshot 2024-12-12 003736](https://github.com/user-attachments/assets/5b8278da-2948-43af-a080-382b01597a4b)

**Additional context**
I couldn't single out mods that would give the same results, since the more I disabled, the more it crashed.

**Comment by dragon3025** [comment]
I'm sorry about the bug everyone. It was working on my PC when I published it.

I want to revert to the last version that worked for everyone, before trying to fix the current. Was version 9.10 working for everyone?

**Comment by dragon3025** [comment]
I updated with an attempt to fix the bug. Please let me know if it's working.

The change I made: In ReducedGrinding>Global>Player.cs at line 43: I changed it from `if (Main.LocalPlayer.HasBuff(BuffID.Clairvoyance))` to `if (Player.HasBuff(BuffID.Clairvoyance))`

**Comment by dragon3025** [comment]
I've gotten several reports that this is fixed now.
