### ISSUE TITLE
Terraria consistently stuttering with mod enabled

### ISSUE THREAD

**Issue by VioletRoses** [dragon3025/Reduced-Grinding#4]
Terraria Version: 1.4.3.6
TModLoader Version: 2022.5.103.14 (didn't happen with previous stable release)

**Describe the bug**
The game stutters for a couple frames every second consistently.

**To Reproduce**
1. Load into a world
2. Notice consistent stuttering behavior

**Expected behavior**
No stuttering, my system is way more than powerful enough to handle the game.

**Screenshots**
It's especially noticeable when looking at the trees
https://user-images.githubusercontent.com/35690943/171988670-b2e9c62e-e859-4cb1-9d8b-681a323ba902.mp4

**Additional context**
If it makes any difference, I am running the game on Linux, specifically Fedora 36 with an i5-12400 and a Vega 56 GPU using the latest graphics drivers.

**Comment by VioletRoses** [comment]
Hmm, seems like the video isn't working for some reason. For the sake of time, I just uploaded it as an unlisted youtube video quickly: https://youtu.be/_jdEZM7zQEk

**Comment by dragon3025** [comment]
I noticed you're using other mods, including lights and shadow, which has graphical features. Does my mod work fine on its own? I updated just now. I added a configuration setting in the "Other Section" to allow you to limit how often the game searches for a Sundial. My mod was also searching every tick to see if any player is near a pylon, so I changed it so it only does this while searching for a Sundial.

**Comment by VioletRoses** [comment]
It does stutter with just this mod enabled, i just forgot to disable the other mods for the recording.
It seems like the sundial search is what causes the stutters, I turned it up to 10 ingame minutes and the stutters became much less frequent.

**Comment by dragon3025** [comment]
I'm glad that fixed helped. I ended up swapping the system for an item that you craft at a sundial, so it's not going to search every tile in the game for this anymore.
