### ISSUE TITLE
Invasions are too short when using the improved spawn rate potions.

### ISSUE THREAD

**Issue by ZeldasWetDream** [dragon3025/Reduced-Grinding#6]
I am trying to grind for items from the martian invasion even but the event ends within seconds of mass murdering these little grey f**ks. 

I think a slider to increase the length of invasions would be the most practical to make.

I think a toggle for endless invasions could be another way to help this or maybe an item when held prevents any kills from counting towards invasion progress.

This change would help for people who dont want the increase in drop-rates but still want things like the spawn rate potions.

**Comment by dragon3025** [comment]
I love this idea. I updated my mod, so now Greater and Super Battle Potion max spawn rates will now affect invasion sizes. There's a slider that controls how strongly it affects it with 100% multiplying the size by the max spawn rates and 0% multiplying the size by 1.
