### ISSUE TITLE
Finch staff from tree shaking drop chance

### ISSUE THREAD

**Issue by donko526** [dragon3025/Reduced-Grinding#7]
Terraria Version: 1.4.3.6
TModLoader Version: v2022.6.96.4

Mods Installed
- Reduced Grinding

Describe the bug
Setting finch staff drop chance to 0 makes it so blocks cannot be removed from the world but still give the item when mined.

1. Change the config option "Finch Staff From Tree Shaking" underneath the "Other" config tab to 0.
2. Try to break any block in-game.

I thought setting this option to 0 would disable the drop like most other config options but instead it completely breaks the ability to remove blocks from the world.

**Comment by dragon3025** [comment]
Thanks for this report. I don't know how you ran it at all, when I set it to 0 it would crash my game. I forgot to add a condition that says to not try any drop if it was set to 0. I updated just now with the bugfix. You're problem wasn't a crash though, are you able to pick up blocks with it set to 0?

**Comment by donko526** [comment]
Yes I was able to pick up and place blocks, they just wouldn't be removed from the world. The best way I can think to describe what was happening to me is that I would mine the block, the item would drop, but then the game wouldn't remember to remove the block from the world so I could mine it over and over again. Here's a GIF of what was happening.
![oops](https://user-images.githubusercontent.com/66753661/178124044-0192ee10-ad82-402e-9e97-633fd7996447.gif)

**Comment by dragon3025** [comment]
Alright, but I updated it so is the problem gone now?

**Comment by donko526** [comment]
Yes the problem is gone 👍

**Comment by dragon3025** [comment]
All right, awesome.
